language: generic
sudo: false
env:
  global:
    # GH_TOKEN (pelson)
    - secure: qVn2Vvnl+dWrg0zZEQgt0xmW/XAawTxGtas0QUYnxcaa5fSp2KtKtLjNf/xI+4ghAM/f3rAw1O3K/RfJnzHWqC3/PZ5oYduiO6zflV4Saqe+67mFBaCAyKNpm6kgZc8TNoP+nSuVn1IfJXXeVeT9mRVa1PbX9RGUDBV4DhZZLvGfDQIrRmAUdjRTp3uhFcA4LJIGvaJ8KiHDYKTEjIs+0GCNrEUIjW5xQmyMSRizcOOYsJYew3VnEeT5YvAaAAuk+E7L92tKAerDcxztix7etAUgnFAk2rEdit5IhOruJDQ581ulhGgu/c4rYR6E/kSoBscVQAD4hHi5nceSSzw4khsCYNvGNli4ZRJB/vBQMjzdYlXPmaLvPvvYcu5LBsg+Y80+43UF/RKtJpgRiQgdgjPwfu6e7pSX9ydUq7A+/YM3lFSHqDywmXIYR0RTerzxhgv0Et8H+FuvcFL0qxGkJk8NKZhnJLnCx/FLSZX1XJXaEwsNq9aYxp5AXCCJiDkVTo9017NjMashnNLFkfmo4PPQGDi6B53a9Z9t46Qp6suqw++Eb/Cx0To5O0kQaOBq7xyenLb2kCahBy/8OHwqfnrA00H/zQFsNImG1CWxP/w/lpQ9Xt922jWkoyOxHYZb7oiPkSWnCu46bexxmmd0jtDleOlEU+y1Rvh0IUugMu4=
    # CF_WEBSERVICES_TOKEN
    - secure: E41Ll28ER+sRt7Z4TJNEjN3H55MTzBRqgecelwr/S9Eq7XDDAa5Sf8NJKexDgtCOGE1OeiEUqP+Be0R9DpS5JzAxQ9MSWkUlJ09gM5R+mjiyKuUhrt3VD5gMVhncR/ZNXfGGC/jaJQjxeFqNYTG+YzmRwj7tTu4Musvsf8Vj+2e3w6okYyRScfBRpNEL9ggAqKxSiJm8F2tx4qXIWQynyP0oXJ7VUSgMWp11iWundadsl+pzKNQKk9w+j9KfL0NgMLb7yfO/eD52JJzFuF72o3aPfSru9Lnf5Wf2wSJ1dyMWzU+Me68JM9j7tod3+snKVyi9ZjTDPdIvdMnAMMIjllbeaZNtGkcXaOSHtX1Phuj4i5mpfO5GuPt0Yo7SKzlU36s548ODiNLmZJdLzipVEBFoggQh0qJsDKBCN3QASJx6Ea8LVSRikvw5jvjQ8a6UJ9PaxnmVShImo0K2r4ZHfngLlJaimizaUaryP3LnIlyYBfvmQ3XmAcH66vwkxwHgUmF9ABq+6SRsHWdLn0DnX+wUnzss9BtVR7UEQh4jYKxaC/hkm08T1+h2k1WJ//6WAh1uikVqBE/eJFgo2Ayu5KR1DbC3Bsskv5VS2TTKVzuAMH23/ROtRE1iIUxBVzdBoaNPPW5+5uWD/aqz7Op+SWTIgNcNIh2qpYTcS97GC+o=
install:
  - export CONDA_BASE=http://repo.anaconda.com/miniconda/Miniconda3
  - wget ${CONDA_BASE}-4.6.14-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda activate
  - conda config --set show_channel_urls True
  - conda config --add channels conda-forge
  - conda update --yes conda
  - conda install --yes --quiet --file conda-requirements.txt
  - mkdir -p ~/.conda-smithy/ && echo $GH_TOKEN > ~/.conda-smithy/github.token
  - echo ${STAGED_RECIPES_FEEDSTOCK_TOKEN} > ~/.conda-smithy/conda-forge_staged-recipes.token
  - echo ${APPVEYOR_IS_OK_FEEDSTOCK_TOKEN} > ~/.conda-smithy/conda-forge_appveyor-is-ok.token
  - pip install --no-deps -e .

script:
  # maybe later...
  # - black --check conda_forge_webservices
  # - flake8 conda_forge_webservices
  # - pytest -vv conda_forge_webservices

  - |
    python -u -m conda_forge_webservices.webapp --local &
    cd scripts
    pytest -vvs test_cfep13_endpoints.py
    retval=$?
    kill $(jobs -p)
    exit $retval


  # pytest -vvs test_cfep13_copy.py
  # kill $(jobs -p)
