version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install conda
          command: |
            source .circleci/install_miniconda.sh

      - run:
          name: clean cf-staging
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base
            python .circleci/clean_cf_staging.py

      - run:
          name: update
          command: |
            export PATH=${HOME}/miniconda/bin:$PATH
            source activate base
            update-webservices

workflows:
  version: 2
  hourly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "15 * * * *"
          filters:
            branches:
              only:
                - master
