version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/repo

    steps:
      - run:
          name: update web services
          command: |
            ret=`curl -H "CF_WEBSERVICES_TOKEN: ${CF_WEBSERVICES_TOKEN}" -X POST https://conda-forge.herokuapp.com//conda-webservice-update/cron`
            echo $ret | grep "updated"

workflows:
  version: 2
  hourly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
